main: com.massivecraft.massivelight.MassiveLight
name: MassiveLight
version: 2.0.0
website: https://www.massivecraft.com
authors: [Cayorion]
description: §eMassiveLight is a plugin that fixes light errors. §aCayorion §efrom the minecraft server §aMassiveCraft §eis the lead programmer. Feel free to visit us at §bhttps://www.massivecraft.com
depend: []
load: startup
permissions:
  massivelight.basecommand: {description: use the MassiveLight base command, default: false}
  massivelight.fix: {description: fix light in nearby chunks, default: false}
  massivelight.version: {description: see plugin version, default: false}
