main: com.massivecraft.massivelight.FixLight
name: FixLight
version: 0.2
authors: [Cayorion, alexknvl]
description: FixLight is a plugin that fixes light errors.
depend: []
commands:
  fixlight:
    description: Relights chunks.
    usage: /fixlight <radius>
permissions:
